
#ListenerMode/Procfile
#web: uvicorn app.main:app --host=0.0.0.0 --port=${PORT:-5000}  ##

#FollowupMode/Procfile
#web: uvicorn app.main_followupmode:app --host=0.0.0.0 --port=${PORT:-5000}  ##

#survey mode


web: uvicorn app.main_surveymode:app --host=0.0.0.0 --port=${PORT:-5000}  ##
